const API="https://alex-park-game-programmer.jss123555.chatgpt.site/api/projects",main=document.querySelector("main");
let projects=[],selected=[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const href=p=>`#project/${encodeURIComponent(p.slug)}`;
const snippets=p=>p.codeSnippets?.length?p.codeSnippets:[p.code].filter(Boolean);
function visual(p,mode="card",n=0){const img=n?p.media?.[n-1]?.src:p.coverImage,cap=n?p.media?.[n-1]?.caption:"PROJECT COVER",style=`--project-accent:${esc(p.accent||"#e5484d")};${img?`background-image:linear-gradient(#1113,#1113),url('${esc(img)}');background-size:cover;background-position:center`:""}`;if(mode==="card")return `<div class="projectVisual" style="${style}" role="img" aria-label="Cover for ${esc(p.name)}">${img?"":'<span class="placeholderFlag">ADD COVER IN STUDIO</span>'}<div class="visualGrid"></div><b>${esc(p.kicker)}</b><span class="visualMark">${esc(p.name.slice(0,2).toUpperCase())}</span></div>`;return `<button class="mediaButton" data-lightbox="${n}" aria-label="Enlarge media for ${esc(p.name)}"><div class="caseMedia ${mode}" style="${style}">${img?"":`<span class="placeholderFlag">PLACEHOLDER ${mode==="compare"?"COMPARISON":"SCREENSHOT"}</span>`}<div class="mediaHud"><i></i><i></i><i></i></div><b>${esc(p.name)}</b><small>${esc(img?(cap||"PROJECT MEDIA"):`MEDIA SLOT ${n+1} · ADD IN PORTFOLIO STUDIO`)}</small></div><span class="zoomIcon">＋</span></button>`}
function card(p,i){return `<article class="projectCard"><a href="${href(p)}">${visual(p)}</a><div class="cardIndex">${String(i+1).padStart(2,"0")} / ${esc(p.year)}</div><h3><a href="${href(p)}">${esc(p.name)}</a></h3><p>${esc(p.description)}</p><dl><div><dt>ROLE</dt><dd>${esc(p.role)}</dd></div><div><dt>STACK</dt><dd>${esc(p.engine)} · ${esc(p.language)}</dd></div></dl><div class="tags">${p.tags.map(t=>`<span>${esc(t)}</span>`).join("")}</div><a class="caseLink" href="${href(p)}">View case study <span>↗</span></a></article>`}
function home(){document.querySelector(".siteHeader").hidden=false;const tags=[...new Set(projects.flatMap(p=>p.tags))],shown=selected.length?projects.filter(p=>selected.every(t=>p.tags.includes(t))):projects;main.innerHTML=`<section class="hero" id="top"><div class="eyebrow"><i></i> AVAILABLE FOR OPPORTUNITIES</div><p class="heroRole">GAME PROGRAMMER</p><h1>I build the systems<br>behind <em>great games.</em></h1><p class="lede">I’m Jab Sandee Srisawat, a game programmer focused on responsive gameplay, robust systems, and the technical problem-solving that turns an idea into something players can feel. <strong>[SAMPLE BIO]</strong></p><div class="heroActions"><a class="button primary" href="#work">View projects <span>↘</span></a><a class="button" href="#contact">Contact me</a></div><div class="heroMeta"><span>01 / GAMEPLAY</span><span>02 / SYSTEMS</span><span>03 / TOOLS</span></div></section>
<section class="projectsSection" id="work"><div class="sectionHeading"><div><span class="sectionNo">01 / SELECTED WORK</span><h2>Inside the build.</h2></div><p>Filter by discipline or technology. Select multiple tags to narrow the results.</p></div><div class="filterBar">${tags.map(t=>`<button data-tag="${esc(t)}" class="${selected.includes(t)?"active":""}" aria-pressed="${selected.includes(t)}">${esc(t)}</button>`).join("")}${selected.length?'<button class="clear" data-clear>Clear all ×</button>':""}</div><div class="resultsLine"><span>${String(shown.length).padStart(2,"0")} PROJECT${shown.length===1?"":"S"}</span><span>${selected.length?esc(selected.join(" + ")):"SHOWING ALL WORK"}</span></div><div class="projectGrid">${shown.map(card).join("")}</div>${shown.length?"":'<div class="emptyState"><b>No projects match every selected tag.</b><p>Try removing one filter to broaden the results.</p><button data-clear>Reset filters</button></div>'}</section>
<section class="aboutSection" id="about"><div><span class="sectionNo">02 / ABOUT</span><h2>Curious by default.<br>Precise by practice.</h2></div><div class="aboutCopy"><p>I care about the invisible work that makes a game feel dependable: clear state, useful tools, predictable networking, and feedback that helps a team iterate. This biography is <strong>placeholder copy</strong> awaiting your real background.</p><p>My process moves from a small, measurable question to an instrumented prototype, then toward a reusable system only when the pattern is proven.</p><div class="principles"><span>PROFILE EARLY</span><span>MAKE STATE VISIBLE</span><span>DESIGN FOR ITERATION</span></div></div></section>
<section class="skillsSection"><span class="sectionNo">03 / CAPABILITIES</span><div class="skillsGrid"><div><h3>Programming</h3><p>C++ · C# · Python · Gameplay architecture · Networking fundamentals · AI behavior · Debug tooling</p></div><div><h3>Engines & tools</h3><p>Unreal Engine · Unity · Pygame · Visual Studio · Git · Perforce · Rider · Profilers</p></div><div><h3>Collaboration</h3><p>Technical design · Code reviews · Designer-facing APIs · Documentation · Cross-discipline iteration</p></div></div></section>
<section class="experienceSection" id="experience"><span class="sectionNo">04 / EXPERIENCE & EDUCATION</span><div class="timeline"><article><time>20XX — PRESENT</time><div><h3>[PLACEHOLDER] Game Programmer</h3><p>Studio / organization name · Add role scope and one verified impact statement.</p></div></article><article><time>20XX — 20XX</time><div><h3>[PLACEHOLDER] Degree or Diploma</h3><p>Institution name · Add relevant coursework, team projects, or specialization.</p></div></article></div></section>
<section class="contactSection" id="contact"><span class="sectionNo">05 / CONTACT</span><h2>Let’s build something<br><em>players remember.</em></h2><p>I’m open to game programming opportunities and conversations about gameplay, systems, and tools.</p><a class="emailLink" href="mailto:your.email@example.com">your.email@example.com <span>↗</span></a><div class="socialLinks"><a href="https://github.com/" target="_blank">GitHub ↗</a><a href="https://www.linkedin.com/" target="_blank">LinkedIn ↗</a><span>LINKS ARE PLACEHOLDERS</span></div></section>`;document.querySelectorAll("[data-tag]").forEach(b=>b.onclick=()=>{const t=b.dataset.tag;selected=selected.includes(t)?selected.filter(x=>x!==t):[...selected,t];home();document.getElementById("work").scrollIntoView()});document.querySelectorAll("[data-clear]").forEach(b=>b.onclick=()=>{selected=[];home();document.getElementById("work").scrollIntoView()})}
function lightboxes(p){document.querySelectorAll("[data-lightbox]").forEach(b=>b.onclick=()=>{const n=+b.dataset.lightbox,box=document.createElement("div");box.className="lightbox";box.innerHTML=`<button>Close ×</button><div class="lightboxInner">${visual(p,"single",n)}<p>Click outside or press Escape to close.</p></div>`;box.querySelector(".mediaButton").disabled=true;const close=()=>{box.remove();document.body.style.overflow="";removeEventListener("keydown",key)},key=e=>e.key==="Escape"&&close();box.onclick=close;box.querySelector(".lightboxInner").onclick=e=>e.stopPropagation();box.querySelector("button").onclick=close;addEventListener("keydown",key);document.body.append(box);document.body.style.overflow="hidden"})}
function projectView(p){document.querySelector(".siteHeader").hidden=true;const code=snippets(p);main.innerHTML=`<header class="caseHeader"><a class="brand" href="#top"><span>JSS</span> JAB SANDEE SRISAWAT</a><a href="#work">← All projects</a></header><div class="caseMain"><section class="caseHero" style="--project-accent:${esc(p.accent)}"><span class="sectionNo">CASE STUDY / ${esc(p.year)}</span><p>${esc(p.kicker)}</p><h1>${esc(p.name)}</h1><div class="caseIntro"><p>${esc(p.overview)}</p><dl><div><dt>ROLE</dt><dd>${esc(p.role)}</dd></div><div><dt>ENGINE</dt><dd>${esc(p.engine)}</dd></div><div><dt>LANGUAGE</dt><dd>${esc(p.language)}</dd></div></dl></div></section>${visual(p,"wide")}
<section class="caseBlock"><aside><span>01</span><h2>Project overview</h2></aside><div><p class="largeCopy">${esc(p.description)}</p><div class="responsibilityGrid"><h3>My responsibilities</h3><ul>${p.responsibilities.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></div></section>
${p.sections.map((s,i)=>`<section class="caseBlock"><aside><span>${String(i+2).padStart(2,"0")}</span><h2>${esc(s.title)}</h2></aside><div><p class="largeCopy">${esc(s.body)}</p>${i===1?'<div class="processFlow"><span>QUESTION</span><i>→</i><span>PROTOTYPE</span><i>→</i><span>INSTRUMENT</span><i>→</i><span>ITERATE</span></div>':""}${i===2?`<div class="codeStack">${code.map(c=>`<div class="explainedSnippet">${c.explanation?.trim()?`<p class="snippetExplanation">${esc(c.explanation)}</p>`:""}<pre><div><span>${esc(c.filename)}</span><span>${esc(c.language).toUpperCase()}</span></div><code>${esc(c.snippet)}</code></pre></div>`).join("")}</div>`:""}${i===3?`<div class="compareGrid">${visual(p,"compare",1)}${visual(p,"compare",2)}</div>`:""}</div></section>`).join("")}
<section class="caseBlock"><aside><span>06</span><h2>Systems programmed</h2></aside><div class="systemGrid">${p.systems.map((s,i)=>`<article><span>SYS_${String(i+1).padStart(2,"0")}</span><h3>${esc(s)}</h3><p>[PLACEHOLDER] Add a concise explanation of the system’s boundaries, data flow, and contribution.</p></article>`).join("")}</div></section><section class="mediaGallery">${visual(p,"single",3)}${visual(p,"single",4)}${visual(p,"single",5)}</section><section class="caseBlock"><aside><span>07</span><h2>Team contributions</h2></aside><div><p class="largeCopy">${esc(p.team)}</p><h3>What I learned</h3><ul class="lessons">${p.lessons.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></section><section class="caseCta"><span class="sectionNo">PROJECT LINKS</span><h2>Explore the build.</h2><div>${p.links.map(l=>`<a href="${l.placeholder?"#":esc(l.href)}" ${l.placeholder?'aria-disabled="true"':""}>${esc(l.label)} ↗</a>`).join("")}</div><a class="nextProject" href="#work">Explore all projects →</a></section></div>`;lightboxes(p);scrollTo(0,0)}
function route(){const hash=decodeURIComponent(location.hash.slice(1));if(hash.startsWith("project/")){const p=projects.find(x=>x.slug===hash.slice(8));if(p)return projectView(p)}home();if(hash&&hash!=="top")setTimeout(()=>document.getElementById(hash)?.scrollIntoView(),0)}
fetch(API).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{if(!Array.isArray(d.projects))throw Error();projects=d.projects;route()}).catch(()=>main.innerHTML='<section class="missingProject"><span>CONNECTION ISSUE</span><h1>The portfolio couldn’t load right now.</h1><p>Please refresh in a moment.</p><button onclick="location.reload()">Try again</button></section>');addEventListener("hashchange",route);

