const API="https://alex-park-game-programmer.jss123555.chatgpt.site/api/projects";
const STUDIO="https://alex-park-game-programmer.jss123555.chatgpt.site/studio";
const main=document.querySelector("main");
let projects=[];let selected=[];
const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const snippets=p=>p.codeSnippets?.length?p.codeSnippets:[p.code].filter(Boolean);
function visual(p,label="ADD COVER IN STUDIO"){return `<div class="visual" style="--accent:${esc(p.accent||"#ff385c")};${p.coverImage?`background-image:linear-gradient(#1113,#1113),url('${esc(p.coverImage)}')`:""}">${!p.coverImage?`<span class="placeholder">${label}</span>`:""}<b>${esc(p.kicker)}</b><i>${esc(p.name.slice(0,2).toUpperCase())}</i></div>`}
function card(p,i){return `<article class="card"><a href="#project/${encodeURIComponent(p.slug)}">${visual(p)}</a><small>${String(i+1).padStart(2,"0")} / ${esc(p.year)}</small><h3><a href="#project/${encodeURIComponent(p.slug)}">${esc(p.name)}</a></h3><p>${esc(p.description)}</p><dl><div><dt>ROLE</dt><dd>${esc(p.role)}</dd></div><div><dt>STACK</dt><dd>${esc(p.engine)} · ${esc(p.language)}</dd></div></dl><div class="tags">${p.tags.map(t=>`<span>${esc(t)}</span>`).join("")}</div><a class="caseLink" href="#project/${encodeURIComponent(p.slug)}">View case study ↗</a></article>`}
function home(){const tags=[...new Set(projects.flatMap(p=>p.tags))];const shown=selected.length?projects.filter(p=>selected.every(t=>p.tags.includes(t))):projects;main.innerHTML=`<section class="hero" id="home"><div class="eyebrow"><i></i> AVAILABLE FOR OPPORTUNITIES</div><p class="role">GAME PROGRAMMER</p><h1>I build the systems<br>behind <em>great games.</em></h1><p class="lede">I’m Jab Sandee Srisawat, a game programmer focused on responsive gameplay, robust systems, and the technical problem-solving that turns an idea into something players can feel.</p><div class="actions"><a class="primary" href="#work">View projects ↘</a><a href="#contact">Contact me</a></div></section><section class="work" id="work"><div class="heading"><div><span>01 / SELECTED WORK</span><h2>Inside the build.</h2></div><p>Filter by discipline or technology. Select multiple tags to narrow the results.</p></div><div class="filters">${tags.map(t=>`<button data-tag="${esc(t)}" class="${selected.includes(t)?"active":""}" aria-pressed="${selected.includes(t)}">${esc(t)}</button>`).join("")}</div><div class="results">${String(shown.length).padStart(2,"0")} PROJECT${shown.length===1?"":"S"}</div><div class="grid">${shown.map(card).join("")||"<p>No projects match every selected tag.</p>"}</div></section><section class="about" id="about"><span>02 / ABOUT</span><h2>Programming for the moment-to-moment.</h2><p>I care about readable architecture, useful tools, and game systems that feel responsive in a player’s hands. This portfolio focuses on the decisions, debugging, and iteration behind the final result.</p><div><article><b>GAMEPLAY</b><p>Player mechanics, combat, interaction, controls, and feel.</p></article><article><b>SYSTEMS</b><p>Reusable architecture, data flow, AI, inventory, and multiplayer.</p></article><article><b>TOOLS</b><p>Developer workflows that make iteration faster and safer.</p></article></div></section><section class="contact" id="contact"><span>03 / CONTACT</span><h2>Let’s build something players remember.</h2><p>Replace these placeholder links in Portfolio Studio when your profiles are ready.</p><div><a href="#">Email — placeholder</a><a href="#">GitHub — placeholder</a><a href="#">LinkedIn — placeholder</a></div></section>`;document.querySelectorAll("[data-tag]").forEach(b=>b.addEventListener("click",()=>{const t=b.dataset.tag;selected=selected.includes(t)?selected.filter(x=>x!==t):[...selected,t];home();location.hash="work"}))}
function projectView(p){const code=snippets(p);main.innerHTML=`<section class="caseHero"><a class="back" href="#work">← All projects</a><span>CASE STUDY / ${esc(p.year)}</span><p>${esc(p.kicker)}</p><h1>${esc(p.name)}</h1><div><p>${esc(p.overview)}</p><dl><div><dt>ROLE</dt><dd>${esc(p.role)}</dd></div><div><dt>ENGINE</dt><dd>${esc(p.engine)}</dd></div><div><dt>LANGUAGE</dt><dd>${esc(p.language)}</dd></div></dl></div></section><section class="wide">${visual(p,"PROJECT COVER")}</section><section class="caseBlock"><aside><span>01</span><h2>Project overview</h2></aside><div><p>${esc(p.description)}</p><h3>My responsibilities</h3><ul>${p.responsibilities.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></section>${p.sections.map((s,i)=>`<section class="caseBlock"><aside><span>${String(i+2).padStart(2,"0")}</span><h2>${esc(s.title)}</h2></aside><div><p>${esc(s.body)}</p>${i===2?`<div class="codeStack">${code.map(c=>`<div>${c.explanation?`<p class="explanation">${esc(c.explanation)}</p>`:""}<pre><header><span>${esc(c.filename)}</span><span>${esc(c.language).toUpperCase()}</span></header><code>${esc(c.snippet)}</code></pre></div>`).join("")}</div>`:""}</div></section>`).join("")}<section class="caseBlock"><aside><span>06</span><h2>Systems programmed</h2></aside><div class="systems">${p.systems.map((x,i)=>`<article><span>SYS_${String(i+1).padStart(2,"0")}</span><h3>${esc(x)}</h3></article>`).join("")}</div></section><section class="caseBlock"><aside><span>07</span><h2>Team & lessons</h2></aside><div><p>${esc(p.team)}</p><ul>${p.lessons.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div></section><section class="caseCta"><span>PROJECT LINKS</span><h2>Explore the build.</h2><div>${p.links.map(l=>`<a href="${l.placeholder?"#":esc(l.href)}">${esc(l.label)} ↗</a>`).join("")}</div></section>`;scrollTo(0,0)}
function route(){const hash=decodeURIComponent(location.hash.slice(1));if(hash.startsWith("project/")){const p=projects.find(x=>x.slug===hash.slice(8));if(p)return projectView(p)}home();if(hash&&hash!=="home")setTimeout(()=>document.getElementById(hash)?.scrollIntoView(),0)}
fetch(API).then(r=>{if(!r.ok)throw Error();return r.json()}).then(data=>{if(!Array.isArray(data.projects))throw Error();projects=data.projects;route()}).catch(()=>{main.innerHTML=`<section class="error"><span>CONNECTION ISSUE</span><h1>The portfolio couldn’t reach Portfolio Studio.</h1><p>Your projects are safe. Try refreshing in a moment.</p><button onclick="location.reload()">Try again</button><a href="${STUDIO}">Open Portfolio Studio</a></section>`});
addEventListener("hashchange",route);

